name: sehir_kesif
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2   # ðŸ”¥ BUNU BURAYA EKLE
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.5.0
  google_maps_flutter_platform_interface: ^2.4.0
  cached_network_image: ^3.3.1  # GÃ¶rsel cache iÃ§in
  shimmer: ^3.0.0               # Loading animasyonu
  photo_view: ^0.14.0
  geolocator: ^10.1.0
  http: ^1.1.0
  share_plus: ^7.2.1  # ðŸ”¥ PaylaÅŸma iÃ§in

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see:
# https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:


    - assets/cities/
    - assets/routes/
    - assets/onboarding/
    - assets/placeholder.jpg





  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here, in this
  # "flutter" section.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700